<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="a5472b16ad595d8" failures="0" tests="10" name="firstartifact.Dataprovidertest" time="0.028" errors="1" timestamp="2025-07-25T23:43:38 IST" skipped="0">
  <testcase classname="firstartifact.Dataprovidertest" name="mullogin" time="0.004"/>
  <testcase classname="firstartifact.Dataprovidertest" name="login" time="0.003"/>
  <testcase classname="firstartifact.Dataprovidertest" name="testexternaldata" time="0.002"/>
  <testcase classname="firstartifact.Dataprovidertest" name="login" time="0.002"/>
  <testcase classname="firstartifact.Dataprovidertest" name="login2" time="0.000">
    <error message="
Parameter &#039;username&#039; is required by @Test on method login2 but has not been marked @Optional or defined
in C:\Users\Administrator\eclipse-workspace\firstartifact\testng.xml" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Parameter 'username' is required by @Test on method login2 but has not been marked @Optional or defined
in C:\Users\Administrator\eclipse-workspace\firstartifact\testng.xml
at org.testng.internal.Parameters.createParams(Parameters.java:264)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:352)
at org.testng.internal.Parameters.createParameters(Parameters.java:690)
at org.testng.internal.Parameters.handleParameters(Parameters.java:885)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- login2 -->
  <testcase classname="firstartifact.Dataprovidertest" name="mullogin" time="0.002"/>
  <testcase classname="firstartifact.Dataprovidertest" name="testexternaldata" time="0.005"/>
  <testcase classname="firstartifact.Dataprovidertest" name="testexternaldata" time="0.003"/>
  <testcase classname="firstartifact.Dataprovidertest" name="login" time="0.005"/>
  <testcase classname="firstartifact.Dataprovidertest" name="mullogin" time="0.002"/>
  <system-out>
    <![CDATA[starting with reporter-----
this msg appears in testng reports as well
INFO level message---
WARN level message---]]>
  </system-out>
</testsuite> <!-- firstartifact.Dataprovidertest -->
